export function getFoodEmoji(foodName: string): string {
  const name = foodName.toLowerCase();
  
  if (name.includes('pollo') || name.includes('chicken')) return '🍗';
  if (name.includes('carne') || name.includes('beef') || name.includes('ternera')) return '🥩';
  if (name.includes('pescado') || name.includes('fish') || name.includes('salmón') || name.includes('salmon') || name.includes('atún') || name.includes('tuna')) return '🐟';
  if (name.includes('huevo') || name.includes('egg')) return '🥚';
  if (name.includes('arroz') || name.includes('rice')) return '🍚';
  if (name.includes('pasta') || name.includes('espagueti') || name.includes('macarrones')) return '🍝';
  if (name.includes('pan') || name.includes('bread') || name.includes('tostada')) return '🍞';
  if (name.includes('leche') || name.includes('milk')) return '🥛';
  if (name.includes('queso') || name.includes('cheese')) return '🧀';
  if (name.includes('yogur') || name.includes('yogurt')) return '🥛';
  if (name.includes('manzana') || name.includes('apple')) return '🍎';
  if (name.includes('plátano') || name.includes('banana')) return '🍌';
  if (name.includes('naranja') || name.includes('orange')) return '🍊';
  if (name.includes('fresa') || name.includes('strawberry')) return '🍓';
  if (name.includes('uva') || name.includes('grape')) return '🍇';
  if (name.includes('sandía') || name.includes('watermelon')) return '🍉';
  if (name.includes('piña') || name.includes('pineapple')) return '🍍';
  if (name.includes('tomate') || name.includes('tomato')) return '🍅';
  if (name.includes('lechuga') || name.includes('lettuce') || name.includes('ensalada') || name.includes('salad')) return '🥗';
  if (name.includes('zanahoria') || name.includes('carrot')) return '🥕';
  if (name.includes('brócoli') || name.includes('broccoli')) return '🥦';
  if (name.includes('aguacate') || name.includes('avocado')) return '🥑';
  if (name.includes('patata') || name.includes('potato') || name.includes('papa')) return '🥔';
  if (name.includes('batata') || name.includes('boniato') || name.includes('sweet potato')) return '🍠';
  if (name.includes('maíz') || name.includes('corn')) return '🌽';
  if (name.includes('calabaza') || name.includes('pumpkin')) return '🎃';
  if (name.includes('pepino') || name.includes('cucumber')) return '🥒';
  if (name.includes('pimiento') || name.includes('pepper')) return '🫑';
  if (name.includes('berenjena') || name.includes('eggplant')) return '🍆';
  if (name.includes('espárrago') || name.includes('asparagus')) return '🌿';
  if (name.includes('champiñón') || name.includes('mushroom') || name.includes('seta')) return '🍄';
  if (name.includes('nuez') || name.includes('nut') || name.includes('almendra') || name.includes('almond')) return '🥜';
  if (name.includes('avellana') || name.includes('hazelnut')) return '🌰';
  if (name.includes('cacahuete') || name.includes('peanut') || name.includes('maní')) return '🥜';
  if (name.includes('chocolate') || name.includes('cacao')) return '🍫';
  if (name.includes('miel') || name.includes('honey')) return '🍯';
  if (name.includes('mermelada') || name.includes('jam')) return '🍓';
  if (name.includes('mantequilla') || name.includes('butter')) return '🧈';
  if (name.includes('aceite') || name.includes('oil')) return '🫒';
  if (name.includes('sal') || name.includes('salt')) return '🧂';
  if (name.includes('azúcar') || name.includes('sugar')) return '🍬';
  if (name.includes('café') || name.includes('coffee')) return '☕';
  if (name.includes('té') || name.includes('tea')) return '🍵';
  if (name.includes('agua') || name.includes('water')) return '💧';
  if (name.includes('zumo') || name.includes('juice') || name.includes('jugo')) return '🧃';
  if (name.includes('refresco') || name.includes('soda') || name.includes('cola')) return '🥤';
  if (name.includes('cerveza') || name.includes('beer')) return '🍺';
  if (name.includes('vino') || name.includes('wine')) return '🍷';
  if (name.includes('batido') || name.includes('smoothie') || name.includes('shake')) return '🥤';
  if (name.includes('proteína') || name.includes('protein') || name.includes('whey')) return '🥤';
  if (name.includes('hamburguesa') || name.includes('burger')) return '🍔';
  if (name.includes('pizza')) return '🍕';
  if (name.includes('sandwich') || name.includes('bocadillo')) return '🥪';
  if (name.includes('taco')) return '🌮';
  if (name.includes('burrito')) return '🌯';
  if (name.includes('sushi')) return '🍣';
  if (name.includes('ramen')) return '🍜';
  if (name.includes('curry')) return '🍛';
  if (name.includes('sopa') || name.includes('soup') || name.includes('caldo')) return '🍲';
  if (name.includes('guiso') || name.includes('stew')) return '🍲';
  if (name.includes('tortilla')) return '🍳';
  if (name.includes('bagel')) return '🥯';
  if (name.includes('croissant')) return '🥐';
  if (name.includes('donut') || name.includes('dona')) return '🍩';
  if (name.includes('galleta') || name.includes('cookie')) return '🍪';
  if (name.includes('tarta') || name.includes('cake') || name.includes('pastel')) return '🍰';
  if (name.includes('helado') || name.includes('ice cream')) return '🍨';
  if (name.includes('flan') || name.includes('pudding')) return '🍮';
  if (name.includes('gelatina') || name.includes('jelly')) return '🍮';
  if (name.includes('caramelo') || name.includes('candy')) return '🍬';
  if (name.includes('palomitas') || name.includes('popcorn')) return '🍿';
  if (name.includes('pretzel')) return '🥨';
  if (name.includes('cereales') || name.includes('cereal')) return '🥣';
  if (name.includes('granola') || name.includes('muesli')) return '🥣';
  if (name.includes('avena') || name.includes('oatmeal') || name.includes('oat')) return '🥣';
  if (name.includes('wrap')) return '🌯';
  if (name.includes('falafel')) return '🧆';
  if (name.includes('crepe') || name.includes('pancake') || name.includes('tortita')) return '🥞';
  if (name.includes('waffle')) return '🧇';
  if (name.includes('bacon') || name.includes('tocino')) return '🥓';
  if (name.includes('salchicha') || name.includes('sausage')) return '🌭';
  if (name.includes('jamón') || name.includes('ham')) return '🍖';
  if (name.includes('pavo') || name.includes('turkey')) return '🦃';
  if (name.includes('pato') || name.includes('duck')) return '🦆';
  if (name.includes('marisco') || name.includes('seafood') || name.includes('camarón') || name.includes('shrimp') || name.includes('gamba')) return '🦐';
  if (name.includes('langosta') || name.includes('lobster')) return '🦞';
  if (name.includes('cangrejo') || name.includes('crab')) return '🦀';
  if (name.includes('calamar') || name.includes('squid')) return '🦑';
  if (name.includes('ostra') || name.includes('oyster')) return '🦪';
  if (name.includes('mejillón') || name.includes('mussel')) return '🦪';
  if (name.includes('lentejas') || name.includes('lentil')) return '🫘';
  if (name.includes('frijol') || name.includes('bean') || name.includes('alubia')) return '🫘';
  if (name.includes('garbanzo') || name.includes('chickpea')) return '🫘';
  if (name.includes('guisante') || name.includes('pea')) return '🫛';
  if (name.includes('edamame')) return '🫛';
  if (name.includes('tofu')) return '🧊';
  if (name.includes('tempeh')) return '🥙';
  
  return '🥗';
}
